run:
  timeout: 5m

linters:
  enable:
    # Default linters
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional linters (less strict for existing code)
    - bodyclose
    - dogsled
    - funlen
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - nakedret
    - nolintlint
    - prealloc
    - whitespace
  disable:
    # Disabled to allow existing code patterns
    - dupl          # Too many false positives in similar functions
    - errcheck      # Too strict for existing patterns (e.g., AbortWithError)
    - errorlint     # Existing code uses direct error comparison
    - exhaustive    # Enum exhaustiveness too strict
    - gochecknoinits # init() functions are used for package initialization
    - goconst       # Many legitimate inline strings
    - gosec         # Too strict for integer conversions
    - misspell      # Spanish comments and intentional names
    - noctx         # HTTP requests without context in existing code
    - revive        # Naming conventions differ from generated code
    - unconvert     # Some conversions are intentional for clarity
    - unparam       # Some unused params are for interface compliance

linters-settings:
  govet:
    disable:
      - shadow  # Disabled - too strict for existing code with common error patterns

  gocritic:
    disabled-checks:
      - exitAfterDefer  # Common pattern in main() for handling init errors

  gocyclo:
    min-complexity: 15

  funlen:
    lines: 100
    statements: 50

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  gosec:
    excludes:
      - G104 # Audit errors not checked (we handle this with errcheck)

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf

issues:
  exclude-dirs:
    - graph/model
  exclude-files:
    - ".*_gen\\.go$"
    - "generated\\.go$"
  exclude-rules:
    # Ignore generated files
    - path: graph/generated\.go
      linters:
        - unused
        - funlen
        - gocyclo
    - path: graph/model/models_gen\.go
      linters:
        - unused
    # Test files can have longer functions
    - path: _test\.go
      linters:
        - funlen

  max-issues-per-linter: 50
  max-same-issues: 10
